FROM php:7.4-apache
#ENV TZ="America/Lima"

RUN apt-get update && apt-get install -y --no-install-recommends git npm vim libxml2-dev libzip-dev

RUN pecl install xdebug-3.1.6
RUN docker-php-ext-install -j$(nproc) mysqli pdo pdo_mysql soap zip
RUN docker-php-ext-enable xdebug

RUN a2enmod rewrite

# COMPOSER 
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# USER
ARG MY_USER_ID=1000
ARG MY_USER_NAME=nonroot
ARG MY_GROUP_ID=1000
ARG MY_GROUP_NAME=nonroot
RUN groupadd --gid $MY_GROUP_ID $MY_GROUP_NAME && useradd --uid $MY_USER_ID --gid $MY_GROUP_ID -s /bin/bash -m $MY_USER_NAME && chown -R $MY_USER_ID:$MY_GROUP_ID /var/www/html
USER $MY_USER_NAME
