FROM php:7.4-apache
#ENV TZ="America/Lima"

RUN apt-get update && apt-get install -y --no-install-recommends git npm vim libxml2-dev libzip-dev

RUN pecl install xdebug-2.9.0
RUN docker-php-ext-install -j$(nproc) mysqli pdo pdo_mysql soap zip
RUN docker-php-ext-enable xdebug

RUN a2enmod rewrite

# COMPOSER 
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# USER
#ARG USERNAME=nonroot
#ARG PASSWORD=nonroot
#ARG USER_UID=1000
#ARG USER_GID=$USER_UID
#RUN groupadd --gid $USER_GID $USERNAME && useradd --uid $USER_UID --gid $USER_GID -s /bin/bash -g $USER_GID -m $USERNAME && usermod -aG sudo $USERNAME && echo "$USERNAME:$PASSWORD" | chpasswd

# USER $USERNAME
